version: '3.2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${PORT}
    volumes: 
      - .:/usr/src/
      - /usr/src/node_modules/
    container_name: ni-una-menos-app
    ports:
      - 4005:4005