version: '3.2'

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VITE_MQTT_URL: ${VITE_MQTT_URL}
      VITE_MQTT_USERNAME: ${VITE_MQTT_USERNAME}
      VITE_MQTT_PASSWORD: ${VITE_MQTT_PASSWORD}
      VITE_MQTT_PORT: ${VITE_MQTT_PORT}
    volumes: 
      - .:/usr/src/
      - /usr/src/node_modules/
    container_name: ni-una-menos-app
    ports:
      - 4005:4005